[조민서] 랭킹보드 조회
SamwaMoney/Timetable-Artist-back pull request #26
Opened 2023-07-27 20:24 UTC by rovemin

# 구현 기능
- 랭킹보드 조회 기능 (최고의 시간표, 최악의 시간표, 인기 시간표)

# 구현 상태
- 알고리즘 이동 난이도 코드 추가
- 포스트맨 테스트 완료 https://painted-catboat-bae.notion.site/6a05b6df43cb47a6b26db08aa9167aae?pvs=4
- 기능 구현하면서 랭킹보드 조회 API 문서에서 달라진 부분 수정했습니다.

2023-07-28 00:33 UTC, aoqlsdl requested changes
메서드 관련 코멘트 남겨두었습니다, 늦은 시간까지 고생 많으셨습니다!

2023-07-28 00:33 UTC, aoqlsdl commented on TimeTableArtist/src/main/java/SamwaMoney/TimeTableArtist/Timetable/controller/TimetableController.java
> +    public List<RankingboardGetResponseDto> getRankingboard(@RequestParam("sortType") String sortType) {
p4) 파일 내부에 제가 미리 작성해둔 `public List<TimetableResponseWithLikeDto> getAllTimetablesWithLikeStatus`가 같은 기능을 하는 것 같은데, 혹시 따로 작성하신 이유가 있을까요? 미리 작성해둔 코드가 따로 쓰이는 곳이 없다면 삭제해도 괜찮을 것 같습니다!

2023-07-28 00:33 UTC, aoqlsdl commented on TimeTableArtist/src/main/java/SamwaMoney/TimeTableArtist/Timetable/service/TimetableService.java
> +    public List<RankingboardGetResponseDto> getRankingboardTimetables(String sortType) {
p2) 랭킹보드 조회시 `memberId==null`일 때 `isLiked==false` 처리해두어야 합니다, 그래서 controller에서 `@RequestBody`로 memberId를 받아오려 했던 거구요! 여기에는 관련 처리 내용이 없는 것 같아서요

2023-07-28 00:33 UTC, aoqlsdl commented on TimeTableArtist/src/main/java/SamwaMoney/TimeTableArtist/Timetable/controller/TimetableController.java
> +    public List<RankingboardGetResponseDto> getRankingboard(@RequestParam("sortType") String sortType) {
p1) 다만, 다른 이유가 없다면 `@RequestBody TimetableRankingRequestDto timetableRankingRequestDto`를 통해 memberId를 받아와야 할 것 같습니다. 이유는 다음 코멘트에 설명된 것과 같습니다!

2023-07-29 15:09 UTC, rovemin commented on TimeTableArtist/src/main/java/SamwaMoney/TimeTableArtist/Timetable/controller/TimetableController.java
> +    public List<RankingboardGetResponseDto> getRankingboard(@RequestParam("sortType") String sortType) {
저도 쓰임이 같아서 처음에 TimetableResponseWithLikeDto를 사용하려고 했는데요, TimetableResponseWithLikeDto에 담긴 값이 랭킹보드 조회 시 전달해야 하는 값과 조금 다르더라고요! 그래서 RankingboardGetResponseDto를 새로 만들었습니다!
p1 관련 답변은 아래 코멘트에 남기겠습니다!

2023-07-29 15:10 UTC, rovemin commented on TimeTableArtist/src/main/java/SamwaMoney/TimeTableArtist/Timetable/service/TimetableService.java
> +    public List<RankingboardGetResponseDto> getRankingboardTimetables(String sortType) {
그 부분 다시 추가해보겠습니다!

2023-07-30 09:51 UTC, closed without merging